#!/usr/bin/env python3
"""Scheduler for predictor ablation experiments.

Runs all (task x model_family x variant x seed) combinations sequentially, using a
**fixed split manifest** (all seeds/variants of a task share the same cluster-based
five-fold split, generated by the first run).

Features:
- --seeds 42 43 44, --n-folds 5, --device;
- covers promoter regression / RBS regression / terminator regression / terminator classification;
- schedules both the Evo and CNN–Attention–BiLSTM model families;
- --dry-run (print commands only), --write-shell (also write run_all_ablations.sh);
- seed-stable output directories; completed runs are skipped (never overwritten);
- tasks run sequentially and stop on the first failure;
- no hyperparameter search and no changes to the finalized hyperparameters (BIOPART_DEFAULTS + fixed architecture flags).

Note: Evo tasks must run under the evo-env interpreter; wrap long trainings with
nohup (see --write-shell).
"""

import argparse
import os
import shlex
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Python interpreter (defaults to the current python; Evo tasks also run in the unified
# deepbioparts environment, or as specified via --python)
DEFAULT_PYTHON = os.environ.get("PYTHON", sys.executable)

# ---- Task definitions ----
# (task_id, biopart, task_type, seq_len, raw_data_path, fixed_test_file)
TASKS = [
    {
        "task_id": "promoter_regression",
        "biopart": "promoter",
        "task_type": "regression",
    },
    {
        "task_id": "rbs_regression",
        "biopart": "rbs",
        "task_type": "regression",
    },
    {
        "task_id": "terminator_regression",
        "biopart": "terminator",
        "task_type": "regression",
    },
    {
        "task_id": "terminator_classification",
        "biopart": "terminator",
        "task_type": "classification",
    },
]

# ---- Variant definitions ----
# Evo: (variant_tag, evo_adaptation, pooling_mode)
# ---- Model family registry (extension point) ----
# Each family = {model_type, figure_group, variants, needs_evo_env}
#   - figure_group: 'dl' or 'evo', determining which figure the family is plotted in (DL vs Evo)
#   - variants:
#       * attnbilstm / 1dcnn: list of ablation_variant strings (matching ablation_variant in the model __init__)
#       * evo: list of (variant_tag, evo_adaptation, pooling_mode) tuples
#   - needs_evo_env: whether the evo-env interpreter is required
# To add a family/variant: register it here; a new ablation_variant also needs a branch in the model __init__.
FAMILY_REGISTRY = {
    "evo": {
        "model_type": "evo",
        "figure_group": "evo",
        "needs_evo_env": True,
        "variants": [
            ("full", "lora", "attention"),
            ("head_only", "head_only", "attention"),
            ("mean_pool", "lora", "mean"),
        ],
    },
    "attnbilstm": {
        "model_type": "attnbilstm",
        "figure_group": "dl",
        "needs_evo_env": False,
        "variants": ["full", "no_attention", "no_bilstm", "no_attention_no_bilstm"],
    },
    "1dcnn": {
        "model_type": "1dcnn",
        "figure_group": "dl",
        "needs_evo_env": False,
        "variants": ["full"],  # 1dcnn ablation variants may be added later
    },
}


def _variant_tag(family, variant_spec):
    """Extract the tag used in the directory name from variant_spec."""
    if family == "evo":
        return variant_spec[0]
    return variant_spec  # plain string


def parse_args():
    p = argparse.ArgumentParser(
        description="Predictor ablation scheduler (fixed split, multi-seed, both families)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--seeds", type=int, nargs="+", default=[42, 43, 44],
                   help="Random seeds; all seeds/variants of a task share the same manifest")
    p.add_argument("--n-folds", type=int, default=5, help="Number of cluster-based K-Fold folds")
    p.add_argument("--device", type=str, default="cuda:0", help="Training device")
    p.add_argument("--tasks", type=str, nargs="+",
                   default=[t["task_id"] for t in TASKS],
                   help="Subset of task_ids to run")
    p.add_argument("--families", type=str, nargs="+",
                   default=list(FAMILY_REGISTRY.keys()),
                   choices=list(FAMILY_REGISTRY.keys()),
                   help="Model families to run (registry keys; DL figure = attnbilstm+1dcnn, Evo figure = evo)")
    p.add_argument("--output-root", type=str, default="predictor_checkpoints/ablation",
                   help="Root output directory (seed-stable subdirectories)")
    p.add_argument("--data-override", type=str, default=None,
                   help="Override the training data path for all tasks (for small-scale validation)")
    p.add_argument("--epochs", type=int, default=None,
                   help="Override the number of training epochs (default: train_predictor's 500)")
    p.add_argument("--single-split", action="store_true",
                   help="Skip K-fold CV: train a single model per run (fold==1 as validation, 5x speed-up); statistical units become seeds")
    p.add_argument("--evo-extra", type=str, nargs="*", default=None,
                   help="Extra arguments passed through to the Evo training command (e.g. --gradient_checkpointing --lora_rank 16)")
    p.add_argument("--python", type=str, default=DEFAULT_PYTHON,
                   help="Python interpreter for training subprocesses (point Evo tasks at evo-env)")
    p.add_argument("--evo-python", type=str, default=None,
                   help="Python interpreter for Evo tasks (defaults to --python; Evo requires evo-env)")
    p.add_argument("--dry-run", action="store_true", help="Print commands only, do not execute")
    p.add_argument("--write-shell", action="store_true",
                   help="Also write run_all_ablations.sh (with set -e)")
    p.add_argument("--continue-on-error", action="store_true",
                   help="Continue after a failed run (default: stop on failure)")
    return p.parse_args()


def task_subdir(task):
    """Subdirectory name of a task under output_root."""
    return f"{task['biopart']}_{task['task_type']}"


def run_dir_for(args, task, family, variant_tag, seed):
    """Seed-stable run directory: <root>/<biopart>_<task>/<family>-<variant>/seed_<S>/"""
    return os.path.join(args.output_root, task_subdir(task), f"{family}-{variant_tag}", f"seed_{seed}")


def build_command(args, family, variant_spec, task, seed, run_dir):
    """Build the train_predictor.py subprocess command. Returns (cmd, variant_tag)."""
    reg = FAMILY_REGISTRY[family]
    model_type = reg["model_type"]
    data_path = args.data_override or task.get("data_path")
    if not data_path:
        raise SystemExit(f"--data_path/--data_override is required for task {task_id(task)}")
    cmd = [
        args.python, "scripts/train_predictor.py",
        "--biopart", task["biopart"],
        "--task_type", task["task_type"],
        "--seed", str(seed),
        "--n_folds", str(args.n_folds),
        "--device", args.device,
        "--data_path", data_path,
        "--output_dir", run_dir,
    ]
    if args.epochs is not None:
        cmd += ["--epochs", str(args.epochs)]
    if args.single_split:
        cmd += ["--single_split"]

    if model_type == "evo":
        variant_tag, adapt, pool = variant_spec
        cmd[0] = args.evo_python or args.python
        cmd += ["--model_type", "evo", "--evo_adaptation", adapt, "--pooling_mode", pool]
        # Evo almost always requires gradient checkpointing on a 24 GB consumer GPU;
        # enabled by default, can be overridden via --evo-extra
        if not args.evo_extra or "--gradient_checkpointing" not in args.evo_extra:
            cmd.append("--gradient_checkpointing")
        if args.evo_extra:
            cmd += args.evo_extra
    else:  # attnbilstm / 1dcnn: variant_spec is the ablation_variant string
        variant_tag = variant_spec
        cmd += ["--model_type", model_type, "--ablation_variant", variant_tag]
    return cmd, variant_tag


def is_complete(run_dir, n_folds=None, single_split=False):
    """Determine whether a run is complete.

    The authoritative completion marker is test_results.csv (written only after
    training + inference have both finished).
    - single_split: only fold_1 is required;
    - otherwise: fold_1..fold_K must all exist (backwards-compatible multi-fold check).
    """
    if not os.path.exists(os.path.join(run_dir, "test_results.csv")):
        return False
    if single_split:
        return os.path.isdir(os.path.join(run_dir, "fold_1"))
    if n_folds:
        for k in range(1, n_folds + 1):
            if not os.path.isdir(os.path.join(run_dir, f"fold_{k}")):
                return False
    return True


def enumerate_jobs(args):
    """Enumerate all (task, family, variant_tag, seed, run_dir, cmd) tuples."""
    selected_tasks = [t for t in TASKS if t["task_id"] in args.tasks]
    jobs = []
    for task in selected_tasks:
        for seed in args.seeds:
            for family in args.families:
                reg = FAMILY_REGISTRY[family]
                for variant_spec in reg["variants"]:
                    vtag = _variant_tag(family, variant_spec)
                    rd = run_dir_for(args, task, family, vtag, seed)
                    cmd, _ = build_command(args, family, variant_spec, task, seed, rd)
                    jobs.append((task, family, vtag, seed, rd, cmd))
    return jobs


def main():
    args = parse_args()

    if args.dry_run:
        print("[dry-run] The following commands would be executed sequentially (stop on first failure):\n")

    jobs = enumerate_jobs(args)
    shell_lines = [
        "#!/usr/bin/env bash",
        "set -e",
        f"cd {PROJECT_ROOT}",
        "",
    ]

    n_total = len(jobs)
    n_run = n_skip = n_fail = 0
    print(f"{n_total} runs in total (tasks={args.tasks} families={args.families} seeds={args.seeds} folds={args.n_folds})\n")

    for idx, (task, family, vtag, seed, rd, cmd) in enumerate(jobs, 1):
        label = f"[{idx}/{n_total}] {task['task_id']} | {family}-{vtag} | seed {seed}"
        cmd_str = " ".join(shlex.quote(c) for c in cmd)
        shell_lines.append(f"# {label}")
        shell_lines.append(cmd_str)
        shell_lines.append("")

        if is_complete(rd, args.n_folds, single_split=args.single_split):
            n_skip += 1
            print(f"{label}\n  SKIP (already complete): {rd}")
            continue

        if args.dry_run:
            n_run += 1
            print(f"{label}\n  {cmd_str}\n")
            continue

        print(f"\n{'='*70}\n{label}\n  run_dir: {rd}\n{'='*70}")
        os.makedirs(rd, exist_ok=True)
        rc = subprocess.call(cmd, cwd=str(PROJECT_ROOT))
        if rc != 0:
            n_fail += 1
            msg = f"  FAILED (rc={rc}): {label}\n  cmd: {cmd_str}"
            print(msg, file=sys.stderr)
            if not args.continue_on_error:
                # Still write the shell script (to allow resuming), then stop
                _maybe_write_shell(args, shell_lines)
                sys.exit(f"Scheduling aborted: {msg}")
        else:
            n_run += 1
            print(f"  OK: {label}")

    if args.dry_run:
        print(f"\n[dry-run] Would run {n_run}, skip {n_skip} (already complete).")
    else:
        print(f"\nFinished: {n_run} run, {n_skip} skipped, {n_fail} failed.")

    _maybe_write_shell(args, shell_lines)


def _maybe_write_shell(args, shell_lines):
    if not args.write_shell:
        return
    out_path = Path(args.output_root) / "run_all_ablations.sh"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(shell_lines) + "\n", encoding="utf-8")
    try:
        out_path.chmod(0o755)
    except OSError:
        pass
    print(f"\nShell script written: {out_path} (run long trainings with nohup; make sure the Evo interpreter points at evo-env)")


if __name__ == "__main__":
    main()
