#!/usr/bin/env python3
"""Sequence activity prediction script (prediction only, thin CLI).

Inference and scanning logic live in ``src/evaluation/predictor_inference.py`` and
``src/evaluation/multi_part_scan.py``; plotting in ``src/visualization/scan_plots.py``.
This script only handles argument parsing, dispatch across the four invocation modes,
and persisting results to disk.

Usage:
    # Multi-part joint scan: omit --biopart to run all three models at once
    python scripts/predict.py --sequence ATGCGTGAGGAGGCTATCGATCGATCGATCGATCG

    # Single-part prediction (RBS, 15bp)
    python scripts/predict.py --sequence AAGGAGGTAAAAAAT --biopart rbs

    # Long-sequence sliding window scan (enabled by default)
    python scripts/predict.py --sequence ATGCGTGAGGAGGCTATCGATCGATCG --biopart rbs

    # Batch prediction from CSV (uses default model)
    python scripts/predict.py --data_path ./my_seqs.csv --biopart rbs

    # Specified model + data (evaluation mode)
    python scripts/predict.py \
        --model_dir ./predictor_checkpoints/supervised_model/rbs_CNN_Attn_BiLSTM \
        --data_path ./results/biopart_database/NR_rbs.csv

Output: predictions.csv (with predicted activity, uncertainty, etc.)
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from src.config import SEQ_LENGTHS
from src.evaluation.multi_part_scan import scan_all_bioparts
from src.evaluation.predictor_inference import (
    apply_activity_transform,
    compute_classification_metrics,
    compute_regression_metrics,
    detect_biopart_from_path,
    ensemble_predict,
    find_fold_checkpoints,
    get_default_model_dir,
    load_activity_transform,
    load_label_transform,
    predict_with_sliding_window,
)
from src.visualization import plot_scan_results


# ---------------------------------------------------------------------------
# Command-line arguments
# ---------------------------------------------------------------------------

def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Sequence activity prediction script (prediction only, no plotting, sliding window scan by default)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # --- Input ---
    parser.add_argument("--sequence", type=str, default=None,
                        help="A single DNA sequence (requires --biopart)")
    parser.add_argument("--data_path", type=str, default=None,
                        help="Path to the prediction data CSV")
    parser.add_argument("--model_dir", type=str, default=None,
                        help="Model checkpoint directory (contains fold_1~fold_5 subdirectories)")
    parser.add_argument("--biopart", type=str, default=None,
                        choices=["promoter", "rbs", "terminator"],
                        help="Biological part type. If omitted, all three models are scanned over the sequence (part-finding mode)")

    # --- Output ---
    parser.add_argument("--output_dir", type=str, default=None,
                        help="Output directory (auto-generated by default)")

    # --- Data ---
    parser.add_argument("--seq_col", type=str, default="sequence",
                        help="Sequence column name (default: sequence)")
    parser.add_argument("--label_col", type=str, default="activity",
                        help="Label column name (default: activity)")
    parser.add_argument("--no_label", action="store_true",
                        help="Data has no labels; prediction only")
    parser.add_argument("--classify_threshold", type=float, default=None,
                        help="Classification mode: threshold for binarizing continuous labels")
    parser.add_argument("--merge_data", type=str, nargs="+", default=None,
                        help="Additional CSV files to merge")

    # --- Scanning ---
    parser.add_argument("--scan", action="store_true", default=True,
                        help="Enable sliding window scan (enabled by default)")
    parser.add_argument("--no_scan", action="store_false", dest="scan",
                        help="Disable sliding window scan")
    parser.add_argument("--scan_step", type=int, default=1,
                        help="Sliding window step size in bp (default: 1)")

    # --- Model / device ---
    parser.add_argument("--device", type=str, default="cuda:0",
                        help="Compute device (default: cuda:0)")
    parser.add_argument("--batch_size", type=int, default=256,
                        help="Prediction batch size (default: 256)")

    # --- Transform ---
    parser.add_argument("--no_transform", action="store_true",
                        help="Do not apply the activity transform; output raw model predictions directly")

    return parser.parse_args()


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

def _resolve_model_dir(path_str: str) -> Path:
    """Resolve a model dir string; relative paths resolve against the project root."""
    p = Path(path_str)
    if not p.is_absolute():
        p = PROJECT_ROOT / p
    return p.resolve()


def save_predictions(report_df: pd.DataFrame, output_dir: Path) -> Path:
    """Save the prediction results CSV."""
    data_dir = output_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    report_path = data_dir / "predictions.csv"
    report_df.to_csv(report_path, index=False, float_format="%.6f")
    print(f"\nPrediction report saved: {report_path}")
    return report_path


def print_summary(report_df: pd.DataFrame, output_dir: Path):
    """Print a prediction summary (classification-aware)."""
    print(f"\n{'='*50}")
    print("Prediction complete!")
    for col in ("predicted_activity", "prob_positive", "max_probability"):
        if col in report_df.columns:
            vals = report_df[col]
            print(f"  {col}: range [{vals.min():.4f}, {vals.max():.4f}], mean {vals.mean():.4f}")
            break
    print(f"  Number of results: {len(report_df)}")
    print(f"  Output directory: {output_dir}")
    print(f"{'='*50}")


# ---------------------------------------------------------------------------
# Main function
# ---------------------------------------------------------------------------

def main():
    """Main entry point."""
    args = parse_args()

    # ---- Determine output directory ----
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = PROJECT_ROOT / "results" / "quick_predict" / f"predict_{timestamp}"
    output_dir.mkdir(parents=True, exist_ok=True)

    # ==================================================================
    # Mode 1a: single sequence, no biopart specified -> joint scan with all three models
    # ==================================================================
    if args.sequence and not args.biopart and not args.model_dir:
        sequence = args.sequence.upper().strip()
        invalid_chars = set(sequence) - {'A', 'C', 'G', 'T', 'N'}
        if invalid_chars:
            print(f"Warning: sequence contains non-standard bases: {invalid_chars}")

        seq_len = len(sequence)
        print(f"Input sequence ({seq_len}bp): "
              f"{sequence[:60]}{'...' if seq_len > 60 else ''}")
        print(f"Scan mode: joint scan of all three parts (promoter/rbs/terminator)")
        print(f"Sliding step: {args.scan_step}bp")

        report_df = scan_all_bioparts(
            sequence=sequence,
            device=args.device,
            batch_size=args.batch_size,
            scan_step=args.scan_step,
            no_transform=args.no_transform,
        )

        if report_df.empty:
            return

        report_df.insert(0, 'original_sequence', sequence)
        report_df.insert(1, 'original_length', seq_len)

        save_predictions(report_df, output_dir)
        plot_scan_results(report_df, output_dir)
        print_summary(report_df, output_dir)
        return

    # ==================================================================
    # Mode 1b: single sequence + specified biopart
    # ==================================================================
    if args.sequence:

        biopart = args.biopart
        sequence = args.sequence.upper().strip()
        invalid_chars = set(sequence) - {'A', 'C', 'G', 'T', 'N'}
        if invalid_chars:
            print(f"Warning: sequence contains non-standard bases: {invalid_chars}")

        activity_transform = None if args.no_transform else load_activity_transform(biopart)
        model_dir = _resolve_model_dir(args.model_dir or get_default_model_dir(biopart))

        print(f"Biopart type: {biopart}")
        print(f"Using model: {model_dir}")

        checkpoints = find_fold_checkpoints(model_dir)
        label_transform = load_label_transform(model_dir)
        expected_len = SEQ_LENGTHS.get(biopart, 50)
        seq_len = len(sequence)

        print(f"\nInput sequence ({seq_len}bp): "
              f"{sequence[:60]}{'...' if seq_len > 60 else ''}")
        print(f"Model expected length: {expected_len}bp")
        print(f"Scan mode: {'enabled' if args.scan else 'disabled'}")

        # Long sequence + scan enabled -> sliding window
        if seq_len > expected_len and args.scan:
            report_df = predict_with_sliding_window(
                sequence, biopart, checkpoints, args.device,
                args.batch_size, args.scan_step,
                label_transform, activity_transform,
            )
            report_df.insert(0, 'original_sequence', sequence)
            report_df.insert(1, 'original_length', seq_len)
        else:
            # Short sequence or scan disabled
            if seq_len < expected_len:
                padded = sequence + 'N' * (expected_len - seq_len)
                print(f"  Sequence is short; right-padded with 'N' to {expected_len}bp")
                sequences = [padded]
            elif seq_len > expected_len:
                # Scan disabled but sequence too long: take the central segment
                start = (seq_len - expected_len) // 2
                seq_sub = sequence[start:start + expected_len]
                print(f"  Sequence too long and scan disabled; taking [{start}:{start+expected_len}]")
                sequences = [seq_sub]
            else:
                sequences = [sequence]

            result = ensemble_predict(
                checkpoints=checkpoints, sequences=sequences,
                biopart=biopart, device=args.device,
                batch_size=args.batch_size, label_transform=label_transform,
            )

            if result['task_type'] == 'regression':
                raw_pred = result['mean_pred'][0]
                true_act = apply_activity_transform(
                    np.array([raw_pred]), activity_transform)[0]
                report_df = pd.DataFrame([{
                    'sequence': sequences[0],
                    'original_length': seq_len,
                    'predicted_fitness': float(raw_pred),
                    'predicted_activity': float(true_act),
                    'prediction_std': float(result['std_pred'][0]),
                }])
                print(f"\nPrediction result:")
                print(f"  Raw prediction (fitness): {raw_pred:.6f}")
                if activity_transform:
                    print(f"  Transformed activity (true_activity): {true_act:.6f}")
                print(f"  Prediction uncertainty (std): {result['std_pred'][0]:.6f}")
            else:
                pred_class = result['predicted_classes'][0]
                report_df = pd.DataFrame([{
                    'sequence': sequences[0],
                    'original_length': seq_len,
                    'predicted_class': int(pred_class),
                    'max_probability': float(result['mean_probs'][0].max()),
                }])
                print(f"\nPrediction result: class={pred_class}")

        save_predictions(report_df, output_dir)
        plot_scan_results(report_df, output_dir)
        print_summary(report_df, output_dir)
        return

    # ==================================================================
    # Mode 2: CSV quick predict (--data_path + --biopart, no --model_dir)
    # ==================================================================
    if args.data_path and not args.model_dir:
        if not args.biopart:
            print("Error: without --model_dir, --biopart is required to auto-discover the default model")
            print("  Choices: promoter, rbs, terminator")
            return

        biopart = args.biopart
        activity_transform = None if args.no_transform else load_activity_transform(biopart)
        model_dir = _resolve_model_dir(get_default_model_dir(biopart))

        print(f"Biopart type: {biopart}")
        print(f"Using model: {model_dir}")

        checkpoints = find_fold_checkpoints(model_dir)
        label_transform = load_label_transform(model_dir)
        expected_len = SEQ_LENGTHS.get(biopart, 50)

        data_path = Path(args.data_path).resolve()
        if not data_path.exists():
            raise FileNotFoundError(f"Data file does not exist: {data_path}")

        df = pd.read_csv(data_path)
        if args.seq_col not in df.columns:
            raise ValueError(f"Sequence column '{args.seq_col}' not found in CSV")

        sequences = df[args.seq_col].values
        print(f"\nLoaded data: {data_path}")
        print(f"Number of sequences: {len(sequences)}")
        print(f"Scan mode: {'enabled' if args.scan else 'disabled'}")

        lengths = [len(str(s)) for s in sequences]
        unique_lengths = set(lengths)
        all_match = all(l == expected_len for l in lengths)

        if all_match or not args.scan:
            # All sequence lengths match, or scan disabled -> batch predict directly
            result = ensemble_predict(
                checkpoints=checkpoints,
                sequences=[str(s) for s in sequences],
                biopart=biopart, device=args.device,
                batch_size=args.batch_size,
                label_transform=label_transform,
            )
            if result['task_type'] == 'regression':
                report_df = df.copy()
                report_df['predicted_fitness'] = result['mean_pred']
                report_df['predicted_activity'] = apply_activity_transform(
                    result['mean_pred'], activity_transform)
                report_df['prediction_std'] = result['std_pred']
            else:
                report_df = df.copy()
                report_df['predicted_class'] = result['predicted_classes']
                report_df['prediction_std'] = result['std_logits'].mean(axis=1)
        else:
            # Non-uniform lengths + scan enabled -> process sequence by sequence
            print(f"  Sequence lengths are non-uniform: {unique_lengths}, expected: {expected_len}bp")
            all_reports = []
            for idx, seq in enumerate(sequences):
                seq_str = str(seq).upper()
                if len(seq_str) != expected_len:
                    window_df = predict_with_sliding_window(
                        seq_str, biopart, checkpoints, args.device,
                        args.batch_size, args.scan_step,
                        label_transform, activity_transform,
                    )
                    window_df.insert(0, 'seq_id', idx)
                    window_df.insert(1, 'original_sequence', seq_str)
                    window_df.insert(2, 'original_length', len(seq_str))
                    all_reports.append(window_df)
                else:
                    result = ensemble_predict(
                        checkpoints=checkpoints, sequences=[seq_str],
                        biopart=biopart, device=args.device,
                        batch_size=args.batch_size,
                        label_transform=label_transform,
                    )
                    if result['task_type'] == 'regression':
                        raw = result['mean_pred'][0]
                        true_act = apply_activity_transform(
                            np.array([raw]), activity_transform)[0]
                        row_df = pd.DataFrame([{
                            'seq_id': idx,
                            'original_sequence': seq_str,
                            'original_length': len(seq_str),
                            'start': 0, 'end': len(seq_str),
                            'sequence': seq_str,
                            'predicted_fitness': float(raw),
                            'predicted_activity': float(true_act),
                            'prediction_std': float(result['std_pred'][0]),
                        }])
                    else:
                        row_df = pd.DataFrame([{
                            'seq_id': idx,
                            'original_sequence': seq_str,
                            'original_length': len(seq_str),
                            'start': 0, 'end': len(seq_str),
                            'sequence': seq_str,
                            'predicted_class': int(result['predicted_classes'][0]),
                            'max_probability': float(result['mean_probs'][0].max()),
                        }])
                    all_reports.append(row_df)
            report_df = pd.concat(all_reports, ignore_index=True)

        save_predictions(report_df, output_dir)
        plot_scan_results(report_df, output_dir)
        print_summary(report_df, output_dir)
        return

    # ==================================================================
    # Mode 3: specified model + data (evaluation mode)
    # ==================================================================
    if args.model_dir is None or args.data_path is None:
        print("Error: input parameters are required")
        print()
        print("Usage:")
        print("  1) Multi-part scan: --sequence <SEQ>              (joint scan with all three models)")
        print("  2) Single-part prediction: --sequence <SEQ> --biopart <rbs|promoter|terminator>")
        print("  3) CSV prediction:   --data_path <CSV> --biopart <rbs|promoter|terminator>")
        print("  4) Specified model:  --model_dir <DIR> --data_path <CSV>")
        return

    model_dir = _resolve_model_dir(args.model_dir)
    data_path = Path(args.data_path).resolve()

    if not model_dir.exists():
        raise FileNotFoundError(f"Model directory does not exist: {model_dir}")
    if not data_path.exists():
        raise FileNotFoundError(f"Data file does not exist: {data_path}")

    biopart = args.biopart or detect_biopart_from_path(model_dir)
    print(f"Biopart type: {biopart}")

    checkpoints = find_fold_checkpoints(model_dir)
    print(f"Found {len(checkpoints)} fold models")

    label_transform = load_label_transform(model_dir)
    if label_transform:
        print(f"Found label transform: {label_transform.get('transform', 'unknown')}")

    # Load data
    print(f"\nLoaded data: {data_path}")
    df = pd.read_csv(data_path)

    if args.merge_data:
        for extra_path in args.merge_data:
            extra_path = Path(extra_path).resolve()
            if not extra_path.exists():
                raise FileNotFoundError(f"Merge data file does not exist: {extra_path}")
            print(f"Merging data: {extra_path}")
            extra_df = pd.read_csv(extra_path)
            df = pd.concat([df, extra_df], ignore_index=True)
        print(f"Total samples after merge: {len(df)}")

        unified = np.full(len(df), np.nan, dtype=np.float32)
        sources = []
        if "predicted_class" in df.columns:
            mask = df["predicted_class"].notna()
            unified[mask] = df.loc[mask, "predicted_class"].values.astype(np.float32)
            sources.append(f"predicted_class({mask.sum()} samples)")
        threshold = args.classify_threshold if args.classify_threshold else 95.0
        for col in ["true_activity", "activity"]:
            if col in df.columns:
                mask = np.isnan(unified) & df[col].notna()
                if mask.any():
                    vals = df.loc[mask, col].values.astype(np.float32)
                    unified[mask] = (vals >= threshold).astype(np.float32)
                    sources.append(f"{col}>={threshold}({mask.sum()} samples)")
        df["_unified_label"] = unified
        n_valid = int((~np.isnan(unified)).sum())
        print(f"Label unification: {', '.join(sources)} -> _unified_label ({n_valid} valid samples)")

    if args.seq_col not in df.columns:
        raise ValueError(f"Sequence column '{args.seq_col}' not found in data file")

    sequences = df[args.seq_col].values

    # Determine label column
    label_col = None
    if not args.no_label:
        if "_unified_label" in df.columns:
            label_col = "_unified_label"
            print("Using merged unified label column: _unified_label")
        elif args.label_col in df.columns:
            label_col = args.label_col
        else:
            for candidate in ["activity", "true_activity", "predicted_class"]:
                if candidate in df.columns:
                    label_col = candidate
                    print(f"Label column '{args.label_col}' not found; automatically using '{candidate}'")
                    break

    has_label = label_col is not None
    if has_label:
        labels = df[label_col].values.astype(np.float32)
        valid_mask = ~np.isnan(labels)
        if not valid_mask.all():
            print(f"Warning: {int((~valid_mask).sum())} samples have no valid label and were dropped")
            sequences = sequences[valid_mask]
            labels = labels[valid_mask]
            df = df[valid_mask].reset_index(drop=True)
        print(f"Number of samples: {len(sequences)}, labeled (column: {label_col})")
    else:
        print(f"Number of samples: {len(sequences)}, unlabeled (prediction-only mode)")

    # Classification threshold
    classify_threshold = args.classify_threshold
    if label_col == "_unified_label":
        classify_threshold = None
    elif classify_threshold is None and has_label and label_col == "true_activity" and biopart == "terminator":
        classify_threshold = 95.0
        print(f"terminator classification mode: auto-set threshold {classify_threshold}")

    # Ensemble prediction
    result = ensemble_predict(
        checkpoints=checkpoints, sequences=sequences,
        biopart=biopart, device=args.device,
        batch_size=args.batch_size, label_transform=label_transform,
    )

    data_dir = output_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    results_df = df.copy()

    if result['task_type'] == 'classification':
        num_classes = result['num_classes']
        mean_probs = result['mean_probs']
        predicted_classes = result['predicted_classes']

        results_df["predicted_class"] = predicted_classes
        for c in range(num_classes):
            results_df[f"prob_class_{c}"] = mean_probs[:, c]
        results_df["prediction_std"] = result['std_logits'].mean(axis=1)

        if has_label:
            if classify_threshold is not None:
                true_classes = (labels >= classify_threshold).astype(int)
            else:
                true_classes = labels.astype(int)
            results_df["true_class"] = true_classes
            results_df["correct"] = (predicted_classes == true_classes).astype(int)

            metrics = compute_classification_metrics(true_classes, predicted_classes, mean_probs)
            print(f"\n{'='*50}")
            print(f"Classification evaluation metrics ({biopart}):")
            print(f"{'='*50}")
            for k, v in metrics.items():
                print(f"  {k:12s}: {v:.4f}")
            pd.DataFrame([metrics]).to_csv(data_dir / "metrics.csv", index=False)
            print(f"Metrics saved to: {data_dir / 'metrics.csv'}")

        cols_to_save = [args.seq_col, "predicted_class"]
        for c in range(num_classes):
            cols_to_save.append(f"prob_class_{c}")
        cols_to_save.append("prediction_std")
        if has_label:
            cols_to_save.extend(["true_class", "correct"])
        results_df = results_df[[c for c in cols_to_save if c in results_df.columns]]

    else:
        mean_pred = result['mean_pred']
        std_pred = result['std_pred']

        results_df["predicted_activity"] = mean_pred
        results_df["prediction_std"] = std_pred

        if has_label:
            results_df["true_activity"] = labels
            results_df["residual"] = labels - mean_pred
            results_df["absolute_error"] = np.abs(results_df["residual"])

            metrics = compute_regression_metrics(labels, mean_pred)
            print(f"\n{'='*50}")
            print(f"Evaluation metrics ({biopart}):")
            print(f"{'='*50}")
            for k, v in metrics.items():
                print(f"  {k:12s}: {v:.4f}")
            pd.DataFrame([metrics]).to_csv(data_dir / "metrics.csv", index=False)
            print(f"Metrics saved to: {data_dir / 'metrics.csv'}")

        cols_to_save = [args.seq_col, "predicted_activity", "prediction_std"]
        if has_label:
            cols_to_save.extend(["true_activity", "residual", "absolute_error"])
        results_df = results_df[[c for c in cols_to_save if c in results_df.columns]]

    results_path = data_dir / "predictions.csv"
    results_df.to_csv(results_path, index=False, float_format="%.6f")
    print(f"Prediction results saved to: {results_path}")
    plot_scan_results(results_df, output_dir)
    print_summary(results_df, output_dir)


if __name__ == "__main__":
    main()
